### DISCUSSION TITLE
Bus connectivity

### DISCUSSION THREAD

**Discussion by AlbertMitjans** [qilimanjaro-tech/qililab#347] [General]
Currently the bus contains the following information (ignoring all the `id_` and `category` values):
```yaml
buses:
  - alias: feedline_input_output_bus
    system_control:
      name: readout_system_control
      instruments: [QCM, rs_1]
    port: 1
```
But this information is not complete. Ideally we would like to map a `Bus` to an output of an instrument, such that we could call:
```python
platform.set_parameter(alias="bus_0", parameter=ql.Parameter.OFFSET_I, value=1.0)
```
and the `Bus` knows which sequencer to update (because it knows the output of the instrument, and internally the instruments knows the sequencer-output mapping).

In the runcard, we could do something like:
```yaml
buses:
  - alias: feedline_input_output_bus
    system_control:
      name: readout_system_control
      instruments:
        - alias: QRM1
          outputs: [0, 1]
        - alias: rs_1
          outputs: [0]
        - alias: attenuator
          outputs: [0]
```

However we have the following problem: what if more than one sequencer is mapped to an output / pair of outputs? Should we update both sequencers when doing:
```python
platform.set_parameter(alias="bus_0", parameter=ql.Parameter.OFFSET_I, value=1.0)
```
???
