### ISSUE TITLE
Support specifying sequencer of qblox module in system control

### ISSUE THREAD

**Issue by AlbertMitjans** [qilimanjaro-tech/qililab#224]
### Feature details

Right now, a `Bus` contains a `SystemControl`, which contains a list of instruments to control over:
```yaml
- id_: 1
  category: bus
  alias: feedline_input_output_bus
  system_control:
    id_: 1
    name: readout_system_control
    category: system_control
    instruments: [QRM, rs_1]
```

We need a way to specify which sequencer (which outputs) of the qblox module (in this example de `QRM`) is connected into this bus. Something like:

```yaml
- id_: 1
  category: bus
  alias: feedline_input_output_bus
  system_control:
    id_: 1
    name: readout_system_control
    category: system_control
    instruments:
      - alias: QRM
        outputs: [0, 1]
      - alias: rs_1
```

### How important would you say this feature is?

1: Not important. Would be nice to have.
