### ISSUE TITLE
Support setting gate parameters for each qubit

### ISSUE THREAD

**Issue by AlbertMitjans** [qilimanjaro-tech/qililab#289]
### Feature details

HW people should be able to calibrate the gate parameters for each qubit independently!

Right now `qililab` only accepts generic settings for gates:
```yaml
  gates:
    - name: M
      amplitude: 1.0
      phase: 0
      duration: 6000
      shape:
        name: rectangular
    - name: X
      amplitude: 1.0
      phase: 0
      duration: 100
      shape:
        name: gaussian
        num_sigmas: 4
```

### Implementation

The fastest way I can think of implementing this is the following (let me know if you think of a better and faster way!):

1. The `gates` attribute in the YAML file should contain a dictionary with qubit indices as keys and gate settings as values (the `RuncardSchema` class should be updated accordingly!):
```yaml
  gates:
    0:
      - name: M
        amplitude: 1.0
        phase: 0
        duration: 6000
        shape:
          name: rectangular
      - name: X
        amplitude: 1.0
        phase: 0
        duration: 100
        shape:
          name: gaussian
          num_sigmas: 4
    1:
      - name: M
        amplitude: 1.0
        phase: 0
        duration: 6000
        shape:
          name: rectangular
      - name: X
        amplitude: 1.0
        phase: 0
        duration: 100
        shape:
          name: gaussian
          num_sigmas: 4
```
2. The whole `pulse/hardware_gate` submodule needs to be refactored:
    - Right now a `HardwareGate` contains a **STATIC** attribute that holds the settings of the gate. Given that these settings will now change for each qubit, this implementation is no longer useful!
    - A quick/ugly fix for this is converting the `HardwareGateSettings` class into a dictionary like the one mentioned above, containing settings for all different qubits.
    - The `CircuitToPulses._instantiate_gates_from_settings` will need to be modified, such that it gathers the settings for all the qubits of a specific gate, and it updates the `settings` attribute accordingly:
```python
            gate_class.settings = gate_class.HardwareGateSettings(**settings_dict)
```

### How important would you say this feature is?

3: Very important! Blocking work.
