### ISSUE TITLE
[BUG] runcard_schema fails with new runcard "internal_circuit" settings

### ISSUE THREAD

**Issue by visagim** [qilimanjaro-tech/qililab#322]
### Expected behavior

The runcard "internal_circuit" defines each gate for each qubit instead of defining them generally for the whole qpu. This is needed since we need different pulse calibration for each gate. 
Each gate for each qubit should be read by runcard_schema and loaded (GateSettings / GateFactory)

### Actual behavior

Running code from the soprano experiment examples:
```
import os
from pathlib import Path

from qililab import Experiment, build_platform

fname = os.path.abspath("")
os.environ["RUNCARDS"] = str(Path(fname) / "examples/runcards")
os.environ["DATA"] = str(Path(fname) / "data")

# load platform
runcard_name = "internal_circuit"
platform = build_platform(name=runcard_name)

print(platform.chip)
```

With a list of gates defined for qubit 0 as
```
  gates:
    0:
      - name: M
        amplitude: 1.0
        phase: 0
        duration: 6000
        shape:
          name: rectangular
      - name: X
        amplitude: 1.0
        phase: 0
        duration: 100
        shape:
          name: gaussian
          num_sigmas: 4
```
results in error
```
  File "/home/victor/envs/qililab/lib/python3.10/site-packages/qililab/settings/runcard_schema.py", line 139, in <listcomp>
    self.gates = [self.GateSettings(**gate) for gate in self.gates] if self.gates is not None else None
TypeError: qililab.settings.runcard_schema.RuncardSchema.PlatformSettings.GateSettings() argument after ** must be a mapping, not int
```
No error is returned if one removes the qubit number and loads the gates as before (for all qubits), that is
```
  gates:
    - name: M
      amplitude: 1.0
      phase: 0
      duration: 6000
      shape:
        name: rectangular
    - name: X
      amplitude: 1.0
      phase: 0
      duration: 100
      shape:
        name: gaussian
        num_sigmas: 4
```

### Existing GitHub issues

- [ ] I have searched existing GitHub issues to make sure the issue does not already exist.
