### ISSUE TITLE
Parking operation should be defined in the gate

### ISSUE THREAD

**Issue by fabiques** [qilimanjaro-tech/qililab#388]
### Feature details

Parking operation should be defined by the user for each specific 2qubit gate as a parameter

The runcard should look something like:

``` yml
    (1,0):
      - name: CZ
        amplitude: 1.0
        phase: 0
        duration: 40
        shape:
          name: snz
          t_phi: 1
          b: 0.5
       park:
         qubit_index: 2
         amplitude: 0.23
``` 

### How important would you say this feature is?

None
